export const SOCKET_EVENTS = {
  // Connection
  CONNECTION: 'connection',
  DISCONNECT: 'disconnect',
  CONNECT_ERROR: 'connect_error',

  // Presence
  PRESENCE_ONLINE: 'PRESENCE:ONLINE',
  PRESENCE_OFFLINE: 'PRESENCE:OFFLINE',

  // Time sync
  SYNC_PING: 'SYNC:PING',
  SYNC_PONG: 'SYNC:PONG',

  // Room management
  ROOM_JOIN: 'ROOM:JOIN',
  ROOM_JOINED: 'ROOM:JOINED',
  ROOM_LEAVE: 'ROOM:LEAVE',
  ROOM_MEMBER_JOINED: 'ROOM:MEMBER_JOINED',
  ROOM_MEMBER_LEFT: 'ROOM:MEMBER_LEFT',
  ROOM_HOST_CHANGED: 'ROOM:HOST_CHANGED',
  ROOM_ENDED: 'ROOM:ENDED',
  ROOM_INVITE: 'ROOM:INVITE',
  ROOM_CONTROL_GRANTED: 'ROOM:CONTROL_GRANTED',
  ROOM_CONTROL_REVOKED: 'ROOM:CONTROL_REVOKED',
  ROOM_ERROR: 'ROOM:ERROR',

  // Playback control & Sync barrier
  PLAYBACK_PLAY: 'PLAYBACK:PLAY',
  PLAYBACK_PAUSE: 'PLAYBACK:PAUSE',
  PLAYBACK_SEEK: 'PLAYBACK:SEEK',
  PLAYBACK_NEXT: 'PLAYBACK:NEXT',
  PLAYBACK_PREV: 'PLAYBACK:PREV',
  PLAYBACK_CHANGE_SONG: 'PLAYBACK:CHANGE_SONG',
  PLAYBACK_STATE: 'PLAYBACK:STATE',
  PLAYBACK_DRIFT: 'PLAYBACK:DRIFT',
  PLAYBACK_EMBED_ERROR: 'PLAYBACK:EMBED_ERROR',
  SYNC_LOAD: 'SYNC:LOAD',
  SYNC_READY: 'SYNC:READY',
  SYNC_START: 'SYNC:START',
  BUFFERING_STATE: 'BUFFERING:STATE',
  ROOM_WAITING_FOR_MEMBER: 'ROOM:WAITING_FOR_MEMBER',

  // Queue
  QUEUE_ADD: 'QUEUE:ADD',
  QUEUE_REMOVE: 'QUEUE:REMOVE',
  QUEUE_UPDATED: 'QUEUE:UPDATED',

  // Friend notifications
  FRIEND_REQUEST_RECEIVED: 'FRIEND:REQUEST_RECEIVED',
  FRIEND_REQUEST_ACCEPTED: 'FRIEND:REQUEST_ACCEPTED',
  FRIEND_REQUEST_REJECTED: 'FRIEND:REQUEST_REJECTED',
} as const;

export type SocketEvent = (typeof SOCKET_EVENTS)[keyof typeof SOCKET_EVENTS];
