export const SYNC_CONSTANTS = {
  // Ready Barrier
  READY_BARRIER_TIMEOUT_MS: 4000,
  START_LEAD_BUFFER_MS: 350,

  // Buffering Management
  BUFFERING_PAUSE_THRESHOLD_MS: 6000,

  // Drift Correction
  DRIFT_CHECK_INTERVAL_MS: 3000,
  DRIFT_IGNORE_MS: 200,
  DRIFT_RESTORE_RATE_MS: 200,
  DRIFT_SEEK_THRESHOLD_MS: 800,
  DRIFT_SEEK_COOLDOWN_MS: 4000,
  NUDGE_RATE_FASTER: 1.02,
  NUDGE_RATE_SLOWER: 0.98,
  NORMAL_PLAYBACK_RATE: 1.0,

  // Clock Sync
  PING_SAMPLE_COUNT: 8,
  PING_INTERVAL_MS: 15000,

  // YouTube Config
  YT_PLAYER_WIDTH: 200,
  YT_PLAYER_HEIGHT: 112,
  YT_LOWEST_QUALITY: 'small',
} as const;
